name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: build
        run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: Debbl/game.aiwan.run
          exclude_assets: '.github,.nojekyll'
          publish_branch: main
          publish_dir: dist
          destination_dir: minesweeper
